### ISSUE TITLE
Parse_Loci.py - IndexError: list index out of range

### ISSUE THREAD

**Issue by rlfrench** [dportik/SuperCRUNCH#8]
Hi,

First of all, thanks for developing this pipeline!

I'm using Python 3.9.0, installed via anaconda on Mac OS 10.14.5. I've been trying (unsuccessfully) to run Parse_Loci.py using the following command:

```
python Parse_Loci.py\
 -i ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step1_taxa_all/Cerambycidae_2021.01.16.fasta\
 -o ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step3_loci_target/Output_2021.01.27/\
 -l ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step3_loci_target/Locus-Search-Terms_Markers_Cerambycidae_2021.01.20.txt\
 -t ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step2_taxa_target/Cerambycidae/2021.01.16.b/Matched_Records_Taxon_Names_NoUndetSp.txt

```

Every time I try this, the script starts to run, and the following appears in my terminal window...

```
--------------------------------------------------------------------------------------

Parsing locus information from: 'Locus-Search-Terms_Markers_Cerambycidae_2021.01.20.txt'
	Found 13 loci to search.

--------------------------------------------------------------------------------------

Parsing taxon information from: 'Matched_Records_Taxon_Names_NoUndetSp.txt'
	Found 60 species names and 0 subspecies names.

--------------------------------------------------------------------------------------

Building SQL database: /Users/rowanfrench 1 2/Desktop/PhD/Thesis research/Projects/Insect pheromones/GenBank_dat/Step3_loci_target/Output_2021.01.27/Cerambycidae_2021.sqlite.db
	Added 5,000 records...
	Added 10,000 records...
	Added 15,000 records...
	Added 20,000 records...
	Added 25,000 records...
	Added 30,000 records...
	Added 35,000 records...
	Added 40,000 records...
	Added 45,000 records...
	Added 50,000 records...
	Added 55,000 records...
	Added 60,000 records...
```

... But then I get the following error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/SuperCRUNCH-master/supercrunch-scripts/Parse_Loci.py", line 531, in <module>
    main()
  File "/usr/local/bin/SuperCRUNCH-master/supercrunch-scripts/Parse_Loci.py", line 511, in main
    build_sql_db(args.input, sql_db_name, species, subspecies, args.no_subspecies)
  File "/usr/local/bin/SuperCRUNCH-master/supercrunch-scripts/Parse_Loci.py", line 298, in build_sql_db
    acc, sp, ssp, d, v = parse_fasta_record(line, species, subspecies, no_subspecies)
  File "/usr/local/bin/SuperCRUNCH-master/supercrunch-scripts/Parse_Loci.py", line 254, in parse_fasta_record
    if parts[0].replace("-", "").isalpha() and len(parts) > 1:
IndexError: list index out of range
```

The output consists of two empty folders (Parsed-Fasta-Files & Summary-File) and an SQL database with minimal text  (see attached).

I've also attached my taxon list and my list of target loci for clarity. My fasta file consists of all available GenBank sequences for the family Cerambycidae (~60,000 in total). I've attempted to rerun the script after modifying my target locus list in various ways (e.g., removing the column headers, limiting my locus search to COI), but I continue to get the same error message. I was able to run Taxa_Assessment.py on the same fasta file without issue.

Do you have any suggestions about the possible source of the problem?

[Matched_Records_Taxon_Names_NoUndetSp.txt](https://github.com/dportik/SuperCRUNCH/files/5884049/Matched_Records_Taxon_Names_NoUndetSp.txt)
[Locus-Search-Terms_Markers_Cerambycidae_2021.01.20.txt](https://github.com/dportik/SuperCRUNCH/files/5884053/Locus-Search-Terms_Markers_Cerambycidae_2021.01.20.txt)
[Cerambycidae_2021.sqlite.db.zip](https://github.com/dportik/SuperCRUNCH/files/5884093/Cerambycidae_2021.sqlite.db.zip)

**Comment by dportik** [comment]
Hello,
Sorry to hear this has been causing you issues. Thank you for providing all the details of your analysis - this was very helpful for figuring out the cause of the issue.

Based on what you have sent, I think the problem was caused by the fasta file. There was a problem parsing an entry in the fasta file to obtain the accession, genus + species, and description. Specifically, the word `isolate` is found in the description, but it doesn't match the general scheme for which this term is used. Generally when the words `haplotype`, `strain`, or `isolate` are used in the description line, they are accompanied by an identifier or code. For example:
```
>DQ347107.1 Cornufer papuensis isolate 1013 rhodopsin gene
```

However, if the entry is like this, it would throw the error message you saw:
```
>DQ347107.1 Cornufer papuensis isolate
```

This is clearly a bug in my code. I've just added a fix for this specific issue, which should handle these cases correctly. **Please download the newest version of `Parse_Loci.py`, run it, and let me know if the issue persists.**

**Comment by rlfrench** [comment]
Thanks for your response! Those fixes to Parse_Loci.py solved my Index Error problem, but now I have a new issue.

When I run the same command as before, this appears in my terminal window:

```
--------------------------------------------------------------------------------------

Parsing locus information from: 'Locus-Search-Terms_Markers_Cerambycidae_2021.01.20.txt'


	Locus LABEL terms:
		Abbreviation(s): ABBREVIATION
		Description(s): DESCRIPTION
		Negative Term(s): N/A


	Locus COI terms:
		Abbreviation(s): COI
				COX1
		Description(s): CYTOCHROME OXIDASE I
				CYTOCHROME OXIDASE 1
				CYTOCHROME OXIDASE SUBUNIT I
				CYTOCHROME OXIDASE SUBUNIT 1
				MITOCHONDRION COMPLETE GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
				CYTOCHROME C OXIDASE SUBUNIT I
				CYTOCHROME C OXIDASE SUBUNIT 1
		Negative Term(s): N/A


	Locus COII terms:
		Abbreviation(s): COII
				COX2
		Description(s): CYTOCHROME OXIDASE II
				CYTOCHROME OXIDASE 2
				CYTOCHROME OXIDASE SUBUNIT II
				CYTOCHROME OXIDASE SUBUNIT 2
				MITOCHONDRION COMPLETE GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
				CYTOCHROME C OXIDASE SUBUNIT II
				CYTOCHROME C OXIDASE SUBUNIT 2
		Negative Term(s): N/A


	Locus CYTB terms:
		Abbreviation(s): CYTB
		Description(s): CYT B
				CYTOCHROME B
				MITOCHONDRION COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
		Negative Term(s): N/A


	Locus WNG terms:
		Abbreviation(s): WNG
		Description(s): WINGLESS
		Negative Term(s): N/A


	Locus 12S terms:
		Abbreviation(s): 12S
		Description(s): 12S RIBOSOMAL RNA
				12S RRNA
				WHOLE GENOME SHOTGUN SEQUENCE
				MITOCHONDRION COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
		Negative Term(s): N/A


	Locus 16S terms:
		Abbreviation(s): 16S
		Description(s): 16S RIBOSOMAL RNA
				16S RRNA
				WHOLE GENOME SHOTGUN SEQUENCE
				MITOCHONDRION COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
		Negative Term(s): N/A


	Locus 18S terms:
		Abbreviation(s): 18S
		Description(s): 18S RIBOSOMAL RNA
				18S RRNA
				WHOLE GENOME SHOTGUN SEQUENCE
				MITOCHONDRION COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
		Negative Term(s): N/A


	Locus 28S terms:
		Abbreviation(s): 28S
		Description(s): 28S RIBOSOMAL RNA
				28S RRNA
				WHOLE GENOME SHOTGUN SEQUENCE
				MITOCHONDRION COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
		Negative Term(s): N/A


	Locus EF1A terms:
		Abbreviation(s): EF1A
				EF-1A
				EF-1ALPHA
		Description(s): ELONGATION FACTOR 1 ALPHA
				TRANSCRIPTOME SHOTGUN ASSEMBLY
				TRANSCRIBED RNA SEQUENCE
				WHOLE GENOME SHOTGUN SEQUENCE
		Negative Term(s): N/A


	Locus CAD terms:
		Abbreviation(s): CAD
		Description(s): CARBAMOYLPHOSPHATE SYNTHETASE
				TRANSCRIPTOME SHOTGUN ASSEMBLY
				TRANSCRIBED RNA SEQUENCE
				WHOLE GENOME SHOTGUN SEQUENCE
		Negative Term(s): N/A


	Locus ND2 terms:
		Abbreviation(s): ND2
		Description(s): DEHYDROGENASE SUBUNIT 2
				DEHYDROGENASE SUBUNIT II
				MITOCHONDRION COMPLETE GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
		Negative Term(s): N/A


	Locus TRNALEU terms:
		Abbreviation(s): TRNA-LEU
		Description(s): MITOCHONDRION COMPLETE GENOME
				MITOCHONDRIAL DNA COMPLETE GENOME
				MITOCHONDRION PARTIAL GENOME
		Negative Term(s): N/A
	Found 13 loci to search.

--------------------------------------------------------------------------------------

Parsing taxon information from: 'Matched_Records_Taxon_Names.log'
	Found 63 species names and 0 subspecies names.

--------------------------------------------------------------------------------------

Building SQL database: /Users/rowanfrench 1 2/Desktop/PhD/Thesis research/Projects/Insect pheromones/GenBank_dat/Step3_loci_target/Output_2021.01.28/Cerambycidae_2021.sqlite.db
	Added 5,000 records...
	Added 10,000 records...
	Added 15,000 records...
	Added 20,000 records...
	Added 25,000 records...
	Added 30,000 records...
	Added 35,000 records...
	Added 40,000 records...
	Added 45,000 records...
	Added 50,000 records...
	Added 55,000 records...
	Added 60,000 records...

Total time to build SQL database: 0:00:07.927567 (H:M:S)


--------------------------------------------------------------------------------------

Indexing fasta file: 'Cerambycidae_2021.01.16.fasta'
	This could take some time...
```
Then this error message appears:

```
Traceback (most recent call last):
  File "/usr/local/bin/SuperCRUNCH/supercrunch-scripts/Parse_Loci.py", line 550, in <module>
    main()
  File "/usr/local/bin/SuperCRUNCH/supercrunch-scripts/Parse_Loci.py", line 537, in main
    records = index_fasta(args.input)
  File "/usr/local/bin/SuperCRUNCH/supercrunch-scripts/Parse_Loci.py", line 184, in index_fasta
    records = SeqIO.index(f, "fasta")
  File "/opt/miniconda2/envs/py390/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 877, in index
    return _IndexedSeqFileDict(
  File "/opt/miniconda2/envs/py390/lib/python3.9/site-packages/Bio/File.py", line 220, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'MT129307.1'

```
I assumed this error was due to duplicated records of MT129307.1 in my fasta file, so I tried to exclude that accession number by running this:

```
 python Parse_Loci.py\
 -i ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step1_taxa_all/Cerambycidae_2021.01.16.fasta\
 -o ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step3_loci_target/Output_2021.01.28/\
 -l ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step3_loci_target/Locus-Search-Terms_Markers_Cerambycidae_2021.01.20.txt\
 -t ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step2_taxa_target/Cerambycidae/2021.01.16.b/Matched_Records_Taxon_Names.log\
 --exclude ~/Desktop/PhD/Thesis\ research/Projects/Insect\ pheromones/GenBank_dat/Step3_loci_target/Locus-Search-Terms_EXCLUDE_Cerambycidae_2021.01.20.txt
```

But the same error message appeared, and the Parsed-Fasta-Files & Summary-File output directories are empty, as before. 

I've attached my most recent SQL database and my accession number exclusion file below. 


[Locus-Search-Terms_EXCLUDE_Cerambycidae_2021.01.20.txt](https://github.com/dportik/SuperCRUNCH/files/5891496/Locus-Search-Terms_EXCLUDE_Cerambycidae_2021.01.20.txt)

[Cerambycidae_2021.sqlite.db.zip](https://github.com/dportik/SuperCRUNCH/files/5891495/Cerambycidae_2021.sqlite.db.zip)

**Comment by dportik** [comment]
Yes, as you've guessed there cannot be duplicate accession numbers present in the fasta file. My guess is that your fasta file contains several duplicate accessions, so excluding the one didn't fix the issue. 

This is actually a common problem, and there is a module already available for this purpose. You can use `Remove_Duplicate_Accessions.py` to filter out duplicate accessions from the fasta file. Please see the instructions for this module [**here**](https://github.com/dportik/SuperCRUNCH/wiki/2:-Starting-Sequences#RDR). 

**After you have cleaned the fasta file, please let me know if you encounter any additional issues.**


I also wanted to mention that you should remove the header from your locus search terms file. Any line in that file will search for a gene, in this case it is searching for:
```
	Locus LABEL terms:
		Abbreviation(s): ABBREVIATION
		Description(s): DESCRIPTION
		Negative Term(s): N/A
```
That will result in a nonsense fasta file.


Lastly, you may also wish to reconsider using the search term `CYTOCHROME OXIDASE I`, because it is nested within `CYTOCHROME OXIDASE II`. This will have the unintended effect of retrieving both CO1 and CO2 sequences for your CO1 gene. The same will be true for the other search terms that use and `I` instead of a `1`.

**Comment by rlfrench** [comment]
That did the trick! Thanks for all your help. I'll close this issue.
